router_bgp:
  as: '65001.200'
  router_id: 10.4.29.4
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 4 ecmp 4
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      password: AQQvKeimxJu+uGQ/yYvv9w==
      maximum_routes: 12000
      send_community: all
  address_family_ipv4:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: true
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  neighbors:
    172.17.2.23:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65112.1400'
      description: DC1-POD2-LEAF14A_Ethernet32/1
    172.17.2.31:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65112.1400'
      description: DC1-POD2-LEAF14B_Ethernet32/1
    172.16.2.6:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65100'
      description: SUPER-SPINE1_Ethernet8/1
    172.16.2.70:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65100'
      description: SUPER-SPINE2_Ethernet8/1
    172.16.2.134:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65100'
      description: SUPER-SPINE3_Ethernet8/1
    172.16.2.198:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65100'
      description: SUPER-SPINE4_Ethernet8/1
static_routes:
- vrf: mgmt
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.6.1.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
snmp_server:
  location: AMS DC1 DC1_POD2 DC1-POD2-SPINE4
spanning_tree:
  mode: none
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$82gqIqw8b3nibNrk$MoZO0S8QMQN8uwnR8v48dbGrL0Ec/6q36tSx8y9IsExi4L.HtmokW9rX8VehLxhg542mNTBKqxMBF.LgnCTm4.
vrfs:
  mgmt:
    ip_routing: false
management_interfaces:
  Management0:
    description: oob_management
    shutdown: false
    vrf: mgmt
    ip_address: 192.168.1.16/24
    gateway: 10.6.1.1
    type: oob
management_api_http:
  enable_vrfs:
    mgmt: {}
  enable_https: true
eos_cli: "interface Loopback1111\n  description Loopback created from raw_eos_cli
  under platform_settings vEOS-LAB\n"
ethernet_interfaces:
  Ethernet7:
    peer: DC1-POD2-LEAF14A
    peer_interface: Ethernet32/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-POD2-LEAF14A_Ethernet32/1
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.2.22/31
  Ethernet8:
    peer: DC1-POD2-LEAF14B
    peer_interface: Ethernet32/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-POD2-LEAF14B_Ethernet32/1
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.2.30/31
  Ethernet29/1:
    peer: SUPER-SPINE1
    peer_interface: Ethernet8/1
    peer_type: super-spine
    description: P2P_LINK_TO_SUPER-SPINE1_Ethernet8/1
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.16.2.7/31
  Ethernet30/1:
    peer: SUPER-SPINE2
    peer_interface: Ethernet8/1
    peer_type: super-spine
    description: P2P_LINK_TO_SUPER-SPINE2_Ethernet8/1
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.16.2.71/31
  Ethernet31/1:
    peer: SUPER-SPINE3
    peer_interface: Ethernet8/1
    peer_type: super-spine
    description: P2P_LINK_TO_SUPER-SPINE3_Ethernet8/1
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.16.2.135/31
  Ethernet32/1:
    peer: SUPER-SPINE4
    peer_interface: Ethernet8/1
    peer_type: super-spine
    description: P2P_LINK_TO_SUPER-SPINE4_Ethernet8/1
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.16.2.199/31
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 10.4.29.4/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 10.4.29.0/24 eq 32
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
