router_bgp:
  as: '65112.100'
  router_id: 10.4.2.3
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 16 ecmp 16
  peer_groups:
    MLAG-IPv4-UNDERLAY-PEER:
      type: ipv4
      remote_as: '65112.100'
      next_hop_self: true
      password: vnEaG8gMeQf3d3cN6PktXQ==
      maximum_routes: 12000
      send_community: all
      route_map_in: RM-MLAG-PEER-IN
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      password: AQQvKeimxJu+uGQ/yYvv9w==
      maximum_routes: 12000
      send_community: all
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      ebgp_multihop: '5'
      password: q+VNViP5i4rVjW1cxFv2wA==
      send_community: all
      maximum_routes: 0
      next_hop_unchanged: true
  address_family_ipv4:
    peer_groups:
      MLAG-IPv4-UNDERLAY-PEER:
        activate: true
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false
  neighbors:
    172.20.2.1:
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: DC1-POD2-LEAF1B
    172.17.2.0:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65001.200'
      description: DC1-POD2-SPINE1_Ethernet1/1
    172.17.2.2:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65001.200'
      description: DC1-POD2-SPINE2_Ethernet1/1
    172.17.2.4:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65001.200'
      description: DC1-POD2-SPINE3_Ethernet1/1
    172.17.2.6:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65001.200'
      description: DC1-POD2-SPINE4_Ethernet1/1
    10.4.2.3:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF1A
      remote_as: '65112.100'
      route_map_out: RM-EVPN-FILTER-AS65112.100
    10.4.2.4:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF1B
      remote_as: '65112.100'
      route_map_out: RM-EVPN-FILTER-AS65112.100
    10.4.2.5:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF2A
      remote_as: '65112.200'
    10.4.2.6:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF2B
      remote_as: '65112.200'
    10.4.2.7:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF3A
      remote_as: '65112.300'
    10.4.2.8:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF3B
      remote_as: '65112.300'
    10.4.2.9:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF4A
      remote_as: '65112.400'
    10.4.2.10:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF4B
      remote_as: '65112.400'
    10.4.2.11:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF5A
      remote_as: '65112.500'
    10.4.2.12:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF5B
      remote_as: '65112.500'
    10.4.2.13:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF6A
      remote_as: '65112.600'
    10.4.2.14:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF6B
      remote_as: '65112.600'
    10.4.2.15:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF7A
      remote_as: '65112.700'
    10.4.2.16:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF7B
      remote_as: '65112.700'
    10.4.2.17:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF8A
      remote_as: '65112.800'
    10.4.2.18:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF8B
      remote_as: '65112.800'
    10.4.2.19:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF9A
      remote_as: '65112.900'
    10.4.2.20:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF9B
      remote_as: '65112.900'
    10.4.2.21:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF10A
      remote_as: '65112.1000'
    10.4.2.22:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF10B
      remote_as: '65112.1000'
    10.4.2.23:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF11A
      remote_as: '65112.1100'
    10.4.2.24:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF11B
      remote_as: '65112.1100'
    10.4.2.25:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF12A
      remote_as: '65112.1200'
    10.4.2.26:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF12B
      remote_as: '65112.1200'
    10.4.2.27:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF13A
      remote_as: '65112.1300'
    10.4.2.28:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF13B
      remote_as: '65112.1300'
    10.4.2.29:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF14A
      remote_as: '65112.1400'
    10.4.2.30:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD2-LEAF14B
      remote_as: '65112.1400'
    11.1.2.3:
      remote_as: '64202'
      description: DC2-POD2-LEAF1B
      peer_group: IPv4-UNDERLAY-PEERS
      local_as: '64201'
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
    route:
      import_match_failure_action: discard
  address_family_rtc:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
        default_route_target:
          only: true
static_routes:
- vrf: mgmt
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.6.1.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
snmp_server:
  location: AMS DC1 DC1_POD2 DC1-POD2-LEAF1A
spanning_tree:
  mode: rstp
  rstp_priority: 4096
  no_spanning_tree_vlan: 4094
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$82gqIqw8b3nibNrk$MoZO0S8QMQN8uwnR8v48dbGrL0Ec/6q36tSx8y9IsExi4L.HtmokW9rX8VehLxhg542mNTBKqxMBF.LgnCTm4.
vrfs:
  mgmt:
    ip_routing: false
management_interfaces:
  Management0:
    description: oob_management
    shutdown: false
    vrf: mgmt
    ip_address: 10.6.34.1/24
    gateway: 10.6.1.1
    type: oob
management_api_http:
  enable_vrfs:
    mgmt: {}
  enable_https: true
eos_cli: "interface Loopback1111\n  description Loopback created from raw_eos_cli
  under platform_settings vEOS-LAB\n"
vlans:
  4094:
    tenant: system
    name: MLAG_PEER
    trunk_groups:
    - MLAG
vlan_interfaces:
  Vlan4094:
    description: MLAG_PEER
    shutdown: false
    ip_address: 172.20.2.0/31
    no_autostate: true
    mtu: 9214
port_channel_interfaces:
  Port-Channel151:
    description: MLAG_PEER_DC1-POD2-LEAF1B_Po151
    type: switched
    shutdown: false
    vlans: 2-4094
    mode: trunk
    service_profile: QOS-PROFILE
    trunk_groups:
    - LEAF_PEER_L3
    - MLAG
ethernet_interfaces:
  Ethernet15/1:
    peer: DC1-POD2-LEAF1B
    peer_interface: Ethernet15/1
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-POD2-LEAF1B_Ethernet15/1
    type: switched
    shutdown: false
    channel_group:
      id: 151
      mode: active
  Ethernet16/1:
    peer: DC1-POD2-LEAF1B
    peer_interface: Ethernet16/1
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-POD2-LEAF1B_Ethernet16/1
    type: switched
    shutdown: false
    channel_group:
      id: 151
      mode: active
  Ethernet29/1:
    peer: DC1-POD2-SPINE1
    peer_interface: Ethernet1/1
    peer_type: spine
    description: P2P_LINK_TO_DC1-POD2-SPINE1_Ethernet1/1
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.2.1/31
  Ethernet30/1:
    peer: DC1-POD2-SPINE2
    peer_interface: Ethernet1/1
    peer_type: spine
    description: P2P_LINK_TO_DC1-POD2-SPINE2_Ethernet1/1
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.2.3/31
  Ethernet31/1:
    peer: DC1-POD2-SPINE3
    peer_interface: Ethernet1/1
    peer_type: spine
    description: P2P_LINK_TO_DC1-POD2-SPINE3_Ethernet1/1
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.2.5/31
  Ethernet32/1:
    peer: DC1-POD2-SPINE4
    peer_interface: Ethernet1/1
    peer_type: spine
    description: P2P_LINK_TO_DC1-POD2-SPINE4_Ethernet1/1
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.2.7/31
  Ethernet28/1:
    peer: DC2-POD2-LEAF1B
    peer_interface: Ethernet28/1
    peer_type: other
    description: P2P_LINK_TO_DC2-POD2-LEAF1B_Ethernet28/1
    type: routed
    shutdown: false
    mtu: 9214
    ip_address: 11.1.2.2/31
mlag_configuration:
  domain_id: RACK1_MLAG
  local_interface: Vlan4094
  peer_address: 172.20.2.1
  peer_address_heartbeat:
    peer_ip: 10.6.34.1
    vrf: mgmt
  dual_primary_detection_delay: 5
  peer_link: Port-Channel151
  reload_delay_mlag: 300
  reload_delay_non_mlag: 330
route_maps:
  RM-MLAG-PEER-IN:
    sequence_numbers:
      10:
        type: permit
        set:
        - origin incomplete
        description: Make routes learned over MLAG Peer-link less preferred on spines
          to ensure optimal routing
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
  RM-EVPN-FILTER-AS65112.100:
    sequence_numbers:
      10:
        type: deny
        match:
        - as 65112.100
      20:
        type: permit
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 10.4.2.3/32
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 10.5.2.3/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 10.4.2.0/24 eq 32
      20:
        action: permit 10.5.2.0/24 eq 32
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
vxlan_interface:
  Vxlan1:
    description: DC1-POD2-LEAF1A_VTEP
    vxlan:
      source_interface: Loopback1
      virtual_router_encapsulation_mac_address: mlag-system-id
      udp_port: 4789
