router_bgp:
  as: '64105'
  router_id: 10.4.1.6
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 4 ecmp 4
  peer_groups:
    MLAG-IPv4-UNDERLAY-PEER:
      type: ipv4
      remote_as: '64105'
      next_hop_self: true
      password: vnEaG8gMeQf3d3cN6PktXQ==
      maximum_routes: 12000
      send_community: all
      route_map_in: RM-MLAG-PEER-IN
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      password: AQQvKeimxJu+uGQ/yYvv9w==
      maximum_routes: 12000
      send_community: all
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      ebgp_multihop: '5'
      password: q+VNViP5i4rVjW1cxFv2wA==
      send_community: all
      maximum_routes: 0
  address_family_ipv4:
    peer_groups:
      MLAG-IPv4-UNDERLAY-PEER:
        activate: true
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false
  neighbors:
    172.20.1.4:
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: DC1-POD1-LEAF5A
    172.17.1.24:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65001.100'
      description: DC1-POD1-SPINE1_Ethernet5
    172.17.1.26:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65001.100'
      description: DC1-POD1-SPINE2_Ethernet5
    172.17.1.28:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65001.100'
      description: DC1-POD1-SPINE3_Ethernet8
    172.17.1.30:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65001.100'
      description: DC1-POD1-SPINE4_Ethernet8
    10.4.1.3:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-POD1-LEAF1B
      remote_as: '65111.100'
      route_map_out: RM-EVPN-FILTER-AS65111.100
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
    route:
      import_match_failure_action: discard
  address_family_rtc:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
  vrfs:
    Common_VRF:
      router_id: 10.4.1.6
      rd: 10.4.1.6:1025
      route_targets:
        import:
          evpn:
          - 1025:1025
        export:
          evpn:
          - 1025:1025
      redistribute_routes:
      - connected
      eos_cli: 'comment

        Comment created from raw_eos_cli under BGP for VRF Common_VRF

        EOF

        '
  vlans:
    110:
      tenant: Tenant_A
      rd: 10.4.1.6:10110
      route_targets:
        both:
        - 10110:10110
      redistribute_routes:
      - learned
    111:
      tenant: Tenant_A
      rd: 10.4.1.6:50111
      route_targets:
        both:
        - 50111:50111
      redistribute_routes:
      - learned
    112:
      tenant: Tenant_A
      rd: 10.4.1.6:50112
      route_targets:
        both:
        - 50112:50112
      redistribute_routes:
      - learned
    2500:
      tenant: Tenant_A
      rd: 10.4.1.6:2500
      route_targets:
        both:
        - 2500:2500
      redistribute_routes:
      - learned
    2600:
      tenant: Tenant_A
      rd: 10.4.1.6:2600
      route_targets:
        both:
        - 2600:2600
      redistribute_routes:
      - learned
static_routes:
- vrf: mgmt
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.6.1.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
snmp_server:
  location: AMS DC1 DC1_POD1 DC1-POD1-LEAF5B
spanning_tree:
  mode: mstp
  mst_instances:
    '0':
      priority: 4096
  no_spanning_tree_vlan: 4094
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$82gqIqw8b3nibNrk$MoZO0S8QMQN8uwnR8v48dbGrL0Ec/6q36tSx8y9IsExi4L.HtmokW9rX8VehLxhg542mNTBKqxMBF.LgnCTm4.
vrfs:
  mgmt:
    ip_routing: false
  Common_VRF:
    tenant: Tenant_A
    ip_routing: true
management_interfaces:
  Management0:
    description: oob_management
    shutdown: false
    vrf: mgmt
    ip_address: 192.168.1.11/16
    gateway: 10.6.1.1
    type: oob
management_api_http:
  enable_vrfs:
    mgmt: {}
  enable_https: true
eos_cli: "interface Loopback1111\n  description Loopback created from raw_eos_cli
  under platform_settings vEOS-LAB\n\ninterface Loopback1000\n  description Loopback
  created from raw_eos_cli under VRF Common_VRF\n"
vlans:
  4094:
    tenant: system
    name: MLAG_PEER
    trunk_groups:
    - MLAG
  110:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_1
  111:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_2
  112:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_3
  113:
    tenant: Tenant_A
    name: SVI_with_no_vxlan
  2500:
    tenant: Tenant_A
    name: web-l2-vlan
  2600:
    tenant: Tenant_A
    name: web-l2-vlan-2
  2601:
    tenant: Tenant_A
    name: l2vlan_with_no_vxlan
vlan_interfaces:
  Vlan4094:
    description: MLAG_PEER
    shutdown: false
    ip_address: 172.20.1.5/31
    no_autostate: true
    mtu: 9214
  Vlan110:
    tenant: Tenant_A
    tags:
    - opzone
    description: set from structured_config on svi (was Tenant_A_OP_Zone_1)
    shutdown: false
    vrf: Common_VRF
    ip_address_virtual: 10.1.10.1/24
    struct_cfg:
      description: set from structured_config on svi (was Tenant_A_OP_Zone_1)
  Vlan111:
    tenant: Tenant_A
    tags:
    - opzone
    description: Tenant_A_OP_Zone_2
    shutdown: true
    vrf: Common_VRF
    ip_address_virtual: 10.1.11.1/24
  Vlan112:
    tenant: Tenant_A
    tags:
    - opzone
    description: Tenant_A_OP_Zone_3
    shutdown: false
    vrf: Common_VRF
    ip_address_virtual: 10.1.12.1/24
    eos_cli: 'comment

      Comment created from raw_eos_cli under SVI 112 in VRF Common_VRF

      EOF

      '
  Vlan113:
    tenant: Tenant_A
    tags:
    - opzone
    description: SVI_with_no_vxlan
    shutdown: false
    vrf: Common_VRF
    ip_address_virtual: 10.10.13.1/24
port_channel_interfaces:
  Port-Channel5:
    description: MLAG_PEER_DC1-POD1-LEAF5A_Po5
    type: switched
    shutdown: false
    vlans: 2-4094
    mode: trunk
    service_profile: QOS-PROFILE
    trunk_groups:
    - LEAF_PEER_L3
    - MLAG
ethernet_interfaces:
  Ethernet5:
    peer: DC1-POD1-LEAF5A
    peer_interface: Ethernet5
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-POD1-LEAF5A_Ethernet5
    type: switched
    shutdown: false
    channel_group:
      id: 5
      mode: active
  Ethernet6:
    peer: DC1-POD1-LEAF5A
    peer_interface: Ethernet6
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-POD1-LEAF5A_Ethernet6
    type: switched
    shutdown: false
    channel_group:
      id: 5
      mode: active
  Ethernet1/1:
    peer: DC1-POD1-SPINE1
    peer_interface: Ethernet5
    peer_type: spine
    description: P2P_LINK_TO_DC1-POD1-SPINE1_Ethernet5
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.1.25/31
  Ethernet1/2:
    peer: DC1-POD1-SPINE2
    peer_interface: Ethernet5
    peer_type: spine
    description: P2P_LINK_TO_DC1-POD1-SPINE2_Ethernet5
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.1.27/31
  Ethernet1/3:
    peer: DC1-POD1-SPINE3
    peer_interface: Ethernet8
    peer_type: spine
    description: P2P_LINK_TO_DC1-POD1-SPINE3_Ethernet8
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.1.29/31
  Ethernet1/4:
    peer: DC1-POD1-SPINE4
    peer_interface: Ethernet8
    peer_type: spine
    description: P2P_LINK_TO_DC1-POD1-SPINE4_Ethernet8
    mtu: 9214
    service_profile: QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.1.31/31
mlag_configuration:
  domain_id: RACK5_MLAG
  local_interface: Vlan4094
  peer_address: 172.20.1.4
  peer_link: Port-Channel5
  reload_delay_mlag: 300
  reload_delay_non_mlag: 330
route_maps:
  RM-MLAG-PEER-IN:
    sequence_numbers:
      10:
        type: permit
        set:
        - origin incomplete
        description: Make routes learned over MLAG Peer-link less preferred on spines
          to ensure optimal routing
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
  RM-EVPN-FILTER-AS65111.100:
    sequence_numbers:
      10:
        type: deny
        match:
        - as 65111.100
      20:
        type: permit
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 10.4.1.6/32
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 10.5.1.5/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 10.4.1.0/24 eq 32
      20:
        action: permit 10.5.1.0/24 eq 32
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
struct_cfg:
  domain_list:
  - structured-config.set.under.vrf.common-vrf
vxlan_interface:
  Vxlan1:
    description: DC1-POD1-LEAF5B_VTEP
    vxlan:
      source_interface: Loopback1
      virtual_router_encapsulation_mac_address: mlag-system-id
      udp_port: 4789
      vlans:
        110:
          vni: 10110
        111:
          vni: 50111
        112:
          vni: 50112
        2500:
          vni: 2500
        2600:
          vni: 2600
      vrfs:
        Common_VRF:
          vni: 1025
domain_list:
- structured-config.set.under.vrf.common-vrf
