router_bgp:
  as: '64801'
  router_id: 10.4.64.10
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 16 ecmp 16
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      password: AQQvKeimxJu+uGQ/yYvv9w==
      maximum_routes: 12000
      send_community: all
  address_family_ipv4:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: true
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  neighbors:
    172.17.64.153:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65101'
      description: DC2-POD1-LEAF1A_Ethernet29/1
    172.17.64.161:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65101'
      description: DC2-POD1-LEAF1B_Ethernet29/1
    172.17.64.177:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65102'
      description: DC2-POD1-LEAF2A_Ethernet29/1
    172.17.64.185:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65102'
      description: DC2-POD1-LEAF2B_Ethernet29/1
    172.17.64.193:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65103'
      description: DC2-POD1-LEAF3A_Ethernet29/1
    172.17.64.201:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65103'
      description: DC2-POD1-LEAF3B_Ethernet29/1
    172.17.64.209:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65104'
      description: DC2-POD1-LEAF4A_Ethernet29/1
    172.17.64.217:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65104'
      description: DC2-POD1-LEAF4B_Ethernet29/1
    172.17.64.225:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65105'
      description: DC2-POD1-LEAF5A_Ethernet29/1
    172.17.64.233:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65105'
      description: DC2-POD1-LEAF5B_Ethernet29/1
    172.17.64.241:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65106'
      description: DC2-POD1-LEAF6A_Ethernet29/1
    172.17.64.249:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65106'
      description: DC2-POD1-LEAF6B_Ethernet29/1
    172.17.65.1:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65107'
      description: DC2-POD1-LEAF7A_Ethernet29/1
    172.17.65.9:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65107'
      description: DC2-POD1-LEAF7B_Ethernet29/1
    172.17.65.17:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65108'
      description: DC2-POD1-LEAF8A_Ethernet29/1
    172.17.65.25:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65108'
      description: DC2-POD1-LEAF8B_Ethernet29/1
    172.17.65.33:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65109'
      description: DC2-POD1-LEAF9A_Ethernet29/1
    172.17.65.41:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65109'
      description: DC2-POD1-LEAF9B_Ethernet29/1
    172.17.65.49:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65110'
      description: DC2-POD1-LEAF10A_Ethernet29/1
    172.17.65.57:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65110'
      description: DC2-POD1-LEAF10B_Ethernet29/1
    172.17.65.65:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65111'
      description: DC2-POD1-LEAF11A_Ethernet29/1
    172.17.65.73:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65111'
      description: DC2-POD1-LEAF11B_Ethernet29/1
    172.17.65.81:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65112'
      description: DC2-POD1-LEAF12A_Ethernet29/1
    172.17.65.89:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65112'
      description: DC2-POD1-LEAF12B_Ethernet29/1
    172.17.65.97:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65113'
      description: DC2-POD1-LEAF13A_Ethernet29/1
    172.17.65.105:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65113'
      description: DC2-POD1-LEAF13B_Ethernet29/1
    172.17.65.113:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65114'
      description: DC2-POD1-LEAF14A_Ethernet29/1
    172.17.65.121:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65114'
      description: DC2-POD1-LEAF14B_Ethernet29/1
    172.16.64.18:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '64501'
      description: SUPER-SPINE1_Ethernet9/1
    172.16.64.82:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '64502'
      description: SUPER-SPINE2_Ethernet9/1
    172.16.64.146:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '64503'
      description: SUPER-SPINE3_Ethernet9/1
    172.16.64.210:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '64504'
      description: SUPER-SPINE4_Ethernet9/1
static_routes:
- vrf: mgmt
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.6.65.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
snmp_server:
  location: AMS DC2 DC2_POD1 DC2-POD1-SPINE1
spanning_tree:
  mode: none
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$82gqIqw8b3nibNrk$MoZO0S8QMQN8uwnR8v48dbGrL0Ec/6q36tSx8y9IsExi4L.HtmokW9rX8VehLxhg542mNTBKqxMBF.LgnCTm4.
vrfs:
  mgmt:
    ip_routing: false
management_interfaces:
  Management0:
    description: oob_management
    shutdown: false
    vrf: mgmt
    ip_address: 10.6.65.10/24
    gateway: 10.6.65.1
    type: oob
management_api_http:
  enable_vrfs:
    mgmt: {}
  enable_https: true
eos_cli: "interface Loopback1111\n  description Loopback created from raw_eos_cli
  under platform_settings vEOS-LAB in AMS.yml\n"
ethernet_interfaces:
  Ethernet1/1:
    peer: DC2-POD1-LEAF1A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF1A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.64.152/31
  Ethernet2/1:
    peer: DC2-POD1-LEAF1B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF1B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.64.160/31
  Ethernet3/1:
    peer: DC2-POD1-LEAF2A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF2A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.64.176/31
  Ethernet4/1:
    peer: DC2-POD1-LEAF2B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF2B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.64.184/31
  Ethernet5/1:
    peer: DC2-POD1-LEAF3A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF3A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.64.192/31
  Ethernet6/1:
    peer: DC2-POD1-LEAF3B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF3B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.64.200/31
  Ethernet7/1:
    peer: DC2-POD1-LEAF4A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF4A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.64.208/31
  Ethernet8/1:
    peer: DC2-POD1-LEAF4B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF4B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.64.216/31
  Ethernet9/1:
    peer: DC2-POD1-LEAF5A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF5A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.64.224/31
  Ethernet10/1:
    peer: DC2-POD1-LEAF5B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF5B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.64.232/31
  Ethernet11/1:
    peer: DC2-POD1-LEAF6A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF6A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.64.240/31
  Ethernet12/1:
    peer: DC2-POD1-LEAF6B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF6B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.64.248/31
  Ethernet13/1:
    peer: DC2-POD1-LEAF7A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF7A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.0/31
  Ethernet14/1:
    peer: DC2-POD1-LEAF7B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF7B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.8/31
  Ethernet15/1:
    peer: DC2-POD1-LEAF8A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF8A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.16/31
  Ethernet16/1:
    peer: DC2-POD1-LEAF8B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF8B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.24/31
  Ethernet17/1:
    peer: DC2-POD1-LEAF9A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF9A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.32/31
  Ethernet18/1:
    peer: DC2-POD1-LEAF9B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF9B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.40/31
  Ethernet19/1:
    peer: DC2-POD1-LEAF10A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF10A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.48/31
  Ethernet20/1:
    peer: DC2-POD1-LEAF10B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF10B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.56/31
  Ethernet21/1:
    peer: DC2-POD1-LEAF11A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF11A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.64/31
  Ethernet22/1:
    peer: DC2-POD1-LEAF11B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF11B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.72/31
  Ethernet23/1:
    peer: DC2-POD1-LEAF12A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF12A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.80/31
  Ethernet24/1:
    peer: DC2-POD1-LEAF12B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF12B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.88/31
  Ethernet25/1:
    peer: DC2-POD1-LEAF13A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF13A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.96/31
  Ethernet26/1:
    peer: DC2-POD1-LEAF13B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF13B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.104/31
  Ethernet27/1:
    peer: DC2-POD1-LEAF14A
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF14A_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.112/31
  Ethernet28/1:
    peer: DC2-POD1-LEAF14B
    peer_interface: Ethernet29/1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC2-POD1-LEAF14B_Ethernet29/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.17.65.120/31
  Ethernet29/1:
    peer: SUPER-SPINE1
    peer_interface: Ethernet9/1
    peer_type: super-spine
    description: P2P_LINK_TO_SUPER-SPINE1_Ethernet9/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.16.64.19/31
  Ethernet30/1:
    peer: SUPER-SPINE2
    peer_interface: Ethernet9/1
    peer_type: super-spine
    description: P2P_LINK_TO_SUPER-SPINE2_Ethernet9/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.16.64.83/31
  Ethernet31/1:
    peer: SUPER-SPINE3
    peer_interface: Ethernet9/1
    peer_type: super-spine
    description: P2P_LINK_TO_SUPER-SPINE3_Ethernet9/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.16.64.147/31
  Ethernet32/1:
    peer: SUPER-SPINE4
    peer_interface: Ethernet9/1
    peer_type: super-spine
    description: P2P_LINK_TO_SUPER-SPINE4_Ethernet9/1
    mtu: 9214
    service_profile: P2P-QOS-PROFILE
    ptp:
      enable: true
    type: routed
    shutdown: false
    ip_address: 172.16.64.211/31
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 10.4.64.10/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 10.4.64.0/24 eq 32
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
