---
fabric_name: AMS

evpn_ebgp_multihop: 5
evpn_overlay_bgp_rtc: true

mgmt_gateway: 10.6.1.1
mgmt_interface: Management0
mgmt_interface_vrf: mgmt
mgmt_destination_networks:
  - 0.0.0.0/0

p2p_uplinks_qos_profile: QOS-PROFILE

local_users:
  admin:
    privilege: 15
    role: network-admin
    no_password: true
    sha512_password: $6$82gqIqw8b3nibNrk$MoZO0S8QMQN8uwnR8v48dbGrL0Ec/6q36tSx8y9IsExi4L.HtmokW9rX8VehLxhg542mNTBKqxMBF.LgnCTm4.

snmp_settings:
  location: true

#What exactly does this do? Border, edge? It is only listed here. There are uplink ipv4 pools elsewhere
l3_edge:
  p2p_links_ip_pools:
    pool-leaf: 11.1.0.0/24
    pool-spine: 11.1.1.0/24
    pool-super-spine: 11.1.2.0/24
  p2p_links_profiles:
    generic-profile:
      #mtu can be specifc here, but the default below gets them
      #this is for snowflakes
      #mtu: 9214
      # Is there a global default for bfd?
      bfd: true
      ptp_enable: true
  p2p_links:
    - nodes: [ DC1-SUPER-SPINE1, DC2-SUPER-SPINE1 ]
      id: 1
      interfaces: [ Ethernet6, Ethernet4 ]
      as: [ 65100, 65200 ]
      ip_pool: pool-super-spine
      profile: generic-profile
      include_in_underlay_protocol: true
      macsec_profile: MACSEC_PROFILE
    - nodes: [ DC1-SUPER-SPINE2, DC2-SUPER-SPINE2 ]
      id: 2
      interfaces: [ Ethernet6, Ethernet4 ]
      as: [ 65100, 65200 ]
      ip_pool: pool-super-spine
      #mtu: 9214
      include_in_underlay_protocol: true
    - nodes: [ DC1-POD2-SPINE1, DC2-POD1-SPINE1 ]
      id: 10
      interfaces: [ Ethernet5, Ethernet5 ]
      as: [ 65120, 65210 ]
      ip_pool: pool-spine
      #mtu: 9214
      include_in_underlay_protocol: true
    - nodes: [ DC1-POD2-SPINE2, DC2-POD1-SPINE2 ]
      interfaces: [ Ethernet4, Ethernet5 ]
      as: [ 65112, 65210 ]
      ip: [ 200.200.200.101/24, 200.200.200.201/24 ]
      #mtu: 9214
      profile: generic-profile
      include_in_underlay_protocol: true
    - nodes: [ DC1-POD1-LEAF2A, DC2-POD1-LEAF1A ]
      interfaces: [ Ethernet7, Ethernet6 ]
      as: [ "65112.100", 65211 ]
      ip: [ 100.100.100.101/24, 100.100.100.201/24 ]
      #mtu: 9214
      include_in_underlay_protocol: true
    - nodes: [ DC1-POD1-LEAF2B, DC2-POD1-LEAF1A ]
      id: 20
      interfaces: [ Ethernet7, Ethernet7 ]
      as: [ 65120, 65211 ]
      ip_pool: pool-leaf
      profile: generic-profile
      #this is a snowflake bfd value
      bfd: false
      include_in_underlay_protocol: true


p2p_uplinks_mtu: 9214

platform_settings:
  - platforms: [default]
    reload_delay:
      mlag: 300
      non_mlag: 330
  - platforms: [vEOS-LAB]
    raw_eos_cli: |
      interface Loopback1111
        description Loopback created from raw_eos_cli under platform_settings vEOS-LAB
    reload_delay:
      mlag: 300
      non_mlag: 330

custom_structured_configuration_list_merge: 'append'

# Node type definitions
node_type_keys:
  spine:
    type: spine
    default_evpn_role: server
    ip_addressing:
      p2p_uplinks_ip: 'ip_addressing/avd-v2-spine-p2p-uplinks-ip.j2'
      p2p_uplinks_peer_ip: 'ip_addressing/avd-v2-spine-p2p-uplinks-peer-ip.j2'
  l3leaf:
    type: l3leaf
    connected_endpoints: true
    default_evpn_role: client
    mlag_support: true
    network_services:
      l2: true
      l3: true
    vtep: true
  l2leaf:
    type: l2leaf
    connected_endpoints: true
    mlag_support: true
    network_services:
      l2: true
    underlay_router: false
    uplink_type: port-channel
  super_spine:
    type: super-spine
  overlay_controller:
    type: overlay-controller
