---
super_spine:
  defaults:
    platform: 7280R
    bgp_as: 65100
    loopback_ipv4_pool: 10.4.27.0/24
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  nodes:
    SUPER-SPINE1:
      id: 1
      platform: 7060
      bgp_as: 64101
      mgmt_ip: "{{ ansible_host }}/24"
      # evpn_role: none
      # evpn_route_servers: []
    SUPER-SPINE2:
      id: 2
      bgp_as: 64102      
      mgmt_ip: "{{ ansible_host }}/24"
      # evpn_role: none
      # evpn_route_servers: []
    SUPER-SPINE3:
      id: 3
      bgp_as: 64103
      mgmt_ip: "{{ ansible_host }}/24"
    SUPER-SPINE4:
      id: 4
      bgp_as: 64104
      mgmt_ip: "{{ ansible_host }}/24"
    SUPER-SPINE5:
      id: 5
      bgp_as: 64105
      mgmt_ip: "{{ ansible_host }}/24"
