---
pod_name: DC2_POD1

max_l3leaf_to_spine_links: 4

spine:
  defaults:
    platform: vEOS-LAB
    bgp_as: "65002.100"
    loopback_ipv4_pool: 10.4.58.0/24    
    uplink_interfaces: ['Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4', 'Ethernet5', 'Ethernet6', 'Ethernet7', 'Ethernet8', 'Ethernet9', 'Ethernet10', 'Ethernet11', 'Ethernet12', 'Ethernet13', 'Ethernet14', 'Ethernet15', 'Ethernet16']
    uplink_switches: ['DC1-SUPER-SPINE1', 'DC1-SUPER-SPINE2', 'DC1-SUPER-SPINE3', 'DC1-SUPER-SPINE4']
    uplink_switch_interfaces: ['Ethernet17/1', 'Ethernet17/2', 'Ethernet17/3', 'Ethernet17/4', 'Ethernet18/1', 'Ethernet18/2', 'Ethernet18/3', 'Ethernet18/4', 'Ethernet19/1', 'Ethernet19/2', 'Ethernet19/3', 'Ethernet19/4', 'Ethernet20/1', 'Ethernet20/2', 'Ethernet20/3', 'Ethernet20/4',]
    max_uplink_switches: 4
    uplink_ipv4_pool: 172.16.32.0/24
    uplink_ptp:
      enable: True
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  nodes:
    DC2-POD1-SPINE1:
      id: 1
      mgmt_ip: 192.168.1.20/24
      evpn_role: none
      uplink_switch_interfaces: ['Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4' ]
    DC2-POD1-SPINE2:
      id: 2
      evpn_role: none
      mgmt_ip: 192.168.1.21/24
      uplink_switch_interfaces: ['Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4']
    DC2-POD1-SPINE3:
      id: 3
      evpn_role: none
      mgmt_ip: 192.168.1.22/24
      uplink_switch_interfaces: ['Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4']
    DC2-POD1-SPINE4:
      id: 4
      evpn_role: none
      mgmt_ip: 10.6.32.4/24
      uplink_switch_interfaces: ['Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4']

# In DC2 we define all variables via defaults
l3leaf:
  defaults:
    bgp_as: 65555
    virtual_router_mac_address: 00:1c:73:00:dc:01  
    platform: vEOS-LAB
    evpn_role: server
    evpn_route_servers: [ DC2-POD1-LEAF1A, DC2-POD1-LEAF1B ]
    spanning_tree_mode: rstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 10.4.32.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 10.5.32.0/24
    uplink_ipv4_pool: 172.17.32.0/24
    uplink_ptp: {'enable': True}
    uplink_interfaces: ['Ethernet1/1', 'Ethernet1/2', 'Ethernet1/3', 'Ethernet1/4', 'Ethernet2/1', 'Ethernet2/2', 'Ethernet2/3', 'Ethernet2/4', 'Ethernet3/1', 'Ethernet3/2', 'Ethernet3/3', 'Ethernet3/4', 'Ethernet4/1', 'Ethernet4/2', 'Ethernet4/3', 'Ethernet4/4', ]
    uplink_switches: ['DC1-POD1-SPINE1', 'DC1-POD1-SPINE2', 'DC1-POD1-SPINE3', 'DC1-POD1-SPINE4']
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    filter:
      always_include_vrfs_in_tenants: [ 'all' ] #Testing that we configure all VRFs even with no VLANs.
      tags: []
    raw_eos_cli: |
      interface Loopback1010
        description Loopback created from raw_eos_cli under l3leaf defaults in DC2 POD1
    mlag: false
    mlag_peer_l3_ipv4_pool: 172.19.32.0/24
    mlag_peer_ipv4_pool: 172.20.32.0/24
  node_groups:
    RACK1_MLAG:
      bgp_as: "65211.100"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF1A:
          id: 1
          mgmt_ip: 192.168.1.7/24 Test without management IP
          # Doesn't seem to be picking up defaults. Wait... this isn't a default. uplink_switch, uplink_interfaces.. but what is this?L2?
          uplink_switch_interfaces: [ Ethernet4, Ethernet5, Ethernet6, Ethernet7 ]
        DC2-POD1-LEAF1B:
          id: 2
          mgmt_ip: 192.168.1.8/24
          uplink_switch_interfaces: [ Ethernet4, Ethernet5, Ethernet6, Ethernet7 ]
    RACK2_MLAG:
      bgp_as: "65211.200"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF2A:
          id: 3
          # mgmt_ip: 192.168.1.8/16 Test without management IP
          uplink_switch_interfaces: [ Ethernet4, Ethernet5, Ethernet6, Ethernet7 ]
        DC2-POD1-LEAF2B:
          id: 4
          mgmt_ip: 192.168.1.9/16
          uplink_switch_interfaces: [ Ethernet4, Ethernet5, Ethernet6, Ethernet7 ]
    RACK3_MLAG:
      bgp_as: "65211.300"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF3A:
          id: 3
          # mgmt_ip: 192.168.1.8/16 Test without management IP
          uplink_switch_interfaces: [ Ethernet4, Ethernet4, Ethernet7, Ethernet7 ]
        DC2-POD1-LEAF3B:
          id: 4
          mgmt_ip: 192.168.1.11/16
          uplink_switch_interfaces: [ Ethernet5, Ethernet5, Ethernet8, Ethernet8 ]
    RACK4_MLAG:
      bgp_as: "65211.400"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF4A:
          id: 3
          # mgmt_ip: 192.168.1.8/16 Test without management IP
          uplink_switch_interfaces: [ Ethernet4, Ethernet4, Ethernet7, Ethernet7 ]
        DC2-POD1-LEAF4B:
          id: 4
          mgmt_ip: 192.168.1.11/16
          uplink_switch_interfaces: [ Ethernet5, Ethernet5, Ethernet8, Ethernet8 ]
    RACK5_MLAG:
      bgp_as: "65211.500"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF5A:
          id: 3
          # mgmt_ip: 192.168.1.8/16 Test without management IP
          uplink_switch_interfaces: [ Ethernet4, Ethernet4, Ethernet7, Ethernet7 ]
        DC2-POD1-LEAF5B:
          id: 4
          mgmt_ip: 192.168.1.11/16
          uplink_switch_interfaces: [ Ethernet5, Ethernet5, Ethernet8, Ethernet8 ]
    RACK6_MLAG:
      bgp_as: "65211.600"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF6A:
          id: 3
          # mgmt_ip: 192.168.1.8/16 Test without management IP
          uplink_switch_interfaces: [ Ethernet4, Ethernet4, Ethernet7, Ethernet7 ]
        DC2-POD1-LEAF6B:
          id: 4
          mgmt_ip: 192.168.1.11/16
          uplink_switch_interfaces: [ Ethernet5, Ethernet5, Ethernet8, Ethernet8 ]
    RACK7_MLAG:
      bgp_as: "65211.700"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF7A:
          id: 3
          # mgmt_ip: 192.168.1.8/16 Test without management IP
          uplink_switch_interfaces: [ Ethernet4, Ethernet4, Ethernet7, Ethernet7 ]
        DC2-POD1-LEAF7B:
          id: 4
          mgmt_ip: 192.168.1.11/16
          uplink_switch_interfaces: [ Ethernet5, Ethernet5, Ethernet8, Ethernet8 ]
    RACK8_MLAG:
      bgp_as: "65211.800"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF8A:
          id: 3
          # mgmt_ip: 192.168.1.8/16 Test without management IP
          uplink_switch_interfaces: [ Ethernet4, Ethernet4, Ethernet7, Ethernet7 ]
        DC2-POD1-LEAF8B:
          id: 4
          mgmt_ip: 192.168.1.11/16
          uplink_switch_interfaces: [ Ethernet5, Ethernet5, Ethernet8, Ethernet8 ] 
    RACK9_MLAG:
      bgp_as: "65211.900"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF9A:
          id: 3
          # mgmt_ip: 192.168.1.8/16 Test without management IP
          uplink_switch_interfaces: [ Ethernet4, Ethernet4, Ethernet7, Ethernet7 ]
        DC2-POD1-LEAF9B:
          id: 4
          mgmt_ip: 192.168.1.11/16
          uplink_switch_interfaces: [ Ethernet5, Ethernet5, Ethernet8, Ethernet8 ] 
    RACK10_MLAG:
      bgp_as: "65211.1000"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF10A:
          id: 3
          # mgmt_ip: 192.168.1.8/16 Test without management IP
          uplink_switch_interfaces: [ Ethernet4, Ethernet4, Ethernet7, Ethernet7 ]
        DC2-POD1-LEAF10B:
          id: 4
          mgmt_ip: 192.168.1.11/16
          uplink_switch_interfaces: [ Ethernet5, Ethernet5, Ethernet8, Ethernet8 ] 
    RACK11_MLAG:
      bgp_as: "65211.1100"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF11A:
          id: 3
          # mgmt_ip: 192.168.1.8/16 Test without management IP
          uplink_switch_interfaces: [ Ethernet4, Ethernet4, Ethernet7, Ethernet7 ]
        DC2-POD1-LEAF11B:
          id: 4
          mgmt_ip: 192.168.1.11/16
          uplink_switch_interfaces: [ Ethernet5, Ethernet5, Ethernet8, Ethernet8 ]                                                   
    RACK12_MLAG:
      bgp_as: "65211.1200"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF12A:
          id: 3
          # mgmt_ip: 192.168.1.8/16 Test without management IP
          uplink_switch_interfaces: [ Ethernet4, Ethernet4, Ethernet7, Ethernet7 ]
        DC2-POD1-LEAF12B:
          id: 4
          mgmt_ip: 192.168.1.11/16
          uplink_switch_interfaces: [ Ethernet5, Ethernet5, Ethernet8, Ethernet8 ]                                                   
    RACK13_MLAG:
      bgp_as: "65211.1300"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF13A:
          id: 3
          # mgmt_ip: 192.168.1.8/16 Test without management IP
          uplink_switch_interfaces: [ Ethernet4, Ethernet4, Ethernet7, Ethernet7 ]
        DC2-POD1-LEAF13B:
          id: 4
          mgmt_ip: 192.168.1.11/16
          uplink_switch_interfaces: [ Ethernet5, Ethernet5, Ethernet8, Ethernet8 ]                                                   
    RACK14_MLAG:
      bgp_as: "65211.1400"
      mlag: true
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 #Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF14A:
          id: 3
          # mgmt_ip: 192.168.1.8/16 Test without management IP
          uplink_switch_interfaces: [ Ethernet4, Ethernet4, Ethernet7, Ethernet7 ]
        DC2-POD1-LEAF14B:
          id: 4
          mgmt_ip: 192.168.1.11/16
          uplink_switch_interfaces: [ Ethernet5, Ethernet5, Ethernet8, Ethernet8 ]                                                   

# In DC2 we define all variables via defaults if possible
l2leaf:
  defaults:
    inband_management_subnet: 172.21.210.0/24
    platform: vEOS-LAB
    uplink_interfaces: [ Ethernet1 ]
    spanning_tree_mode: mstp
    spanning_tree_priority: 8192
    mlag: false
    raw_eos_cli: |
      interface Loopback1011
        description Loopback created from raw_eos_cli under l2leaf defaults in DC2 POD1
  node_groups:
    RACK1_SINGLE:
      uplink_switches: ['DC2-POD1-LEAF1A']
      nodes:
        DC2-POD1-L2LEAF1A:
          id: 1
          mgmt_ip: 192.168.1.23/24
          uplink_switch_interfaces: ['Ethernet3']
