---
port_profiles:
  NESTED_TENANT_A:
    parent_profile: TENANT_A
    raw_eos_cli: |
      comment
      Comment created from raw_eos_cli under profile NESTED_TENANT_A
      EOF
    port_channel:
      raw_eos_cli: |
        comment
        Comment created from raw_eos_cli under port_channel on profile NESTED_TENANT_A
        EOF

  TENANT_A:
    mode: access
    vlans: "110"
    qos_profile: "foo"
#shows up under port 13/1's port-channel config
    raw_eos_cli: |
      comment
      Comment created from raw_eos_cli under profile TENANT_A
      EOF

  TENANT_B:
    mode: access
    vlans: "110"
    qos_profile: "foo"
    port_channel:
      raw_eos_cli: port-channel lacp fallback individual
      state: present
      description: PortChannel
      mode: active

#Is this actual compute or an L2 switch? Seems to be Leafs listed
#what is the scope? How do I make this a template?
# This seems to be literal. Server-1 is one server. Need to check out profiles up above. 
servers:

#"server-1" is prepended to the port-channel description
  server-1:
  #what relevance does "rackB" have?
    rack: RackB
    adapters:
      - server_ports: [ Eth1, Eth2 ]
        switch_ports: [ Ethernet13/1, Ethernet13/1 ]
        switches: [ DC2-POD1-LEAF4A, DC2-POD1-LEAF4B ]
        profile: TENANT_A
        qos_profile: "bar"
# Is there a fallback option?
        port_channel:
          state: present
          description: PortChannel
          mode: active
          raw_eos_cli: port-channel lacp fallback individual
      - server_ports: [ Eth3, Eth4 ]
        switch_ports: [ Ethernet12/1, Ethernet12/1 ]
        switches: [ DC2-POD1-LEAF4A, DC2-POD1-LEAF4B ]
        profile: TENANT_A
        structured_config:
          description: Set using structured_config on server adapter
        port_channel:
          structured_config:
            description: Set using structured_config on server adapter port-channel
          state: present
          description: PortChannel
          mode: active
        raw_eos_cli: |
          comment
          Comment created from raw_eos_cli under adapter for switch Eth17
          EOF

      - server_ports: [ Eth5, Eth6 ]
        switch_ports: [ Ethernet11/1, Ethernet11/1 ]
        switches: [ DC2-POD1-LEAF4A, DC2-POD1-LEAF4B ]
        profile: NESTED_TENANT_A
        port_channel:
          state: present
          description: PortChannel
          mode: active

#This is concise and works:
#But still is a per-server entry. Thousands of these?
  server-2:
    rack: RackB
    adapters:
      - server_ports: [ eno3, eno4 ]
        switch_ports: [ Ethernet10/1, Ethernet10/1 ]
        switches: [ DC2-POD1-LEAF4A, DC2-POD1-LEAF4B ]
        profile: TENANT_B

