---
# DC Tenants (Customers)
# Documentation of Tenant/Customer specific information - Vlans/VRFs
tenants:
  # Tenant A Specific Information - VRFs / VLANs
  Cust_A:
    mac_vrf_vni_base: 10000
    # MLAG IBGP peering per VRF | Optional
    # By default an IBGP peering is configured per VRF between MLAG peers on separate VLANs.
    # Setting enable_mlag_ibgp_peering_vrfs: false under tenant will change this default to prevent configuration of these peerings and VLANs for all VRFs in the tenant.
    # This setting can be overridden per VRF.
    enable_mlag_ibgp_peering_vrfs: true
    vrfs:
      Cust_A_VRF:
        vrf_vni: 1025
      # IP Helper for DHCP relay
#        ip_helpers:
#          < IPv4 dhcp server IP >:
#            source_interface: < interface-name >
#            source_vrf: < VRF to originate DHCP relay packets to DHCP server. If not set, uses current VRF >
# This will create both the L3 SVI and L2 VLAN based on filters applied to l3leaf and l2leaf.
        svis:
          "100":
            name: Cust_A_OP_Zone_1
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.0.10.1/24
            structured_config:
              description: set from structured_config on svi (was Cust_A_OP_Zone_1)
# Everyone gets this, the node list calls out special configuration
#            nodes:
#              DC1-POD1-LEAF2A:
#                structured_config:
#                  description: set from structured_config on svi for DC1-POD1-LEAF2A (was Cust_A_OP_Zone_1)
          "111":
#            vni_override: 50111
            name: Cust_A_OP_Zone_2
            tags: [opzone]
            ip_address_virtual: 10.1.11.1/24
          "112":
#            vni_override: 50112
            name: Cust_A_OP_Zone_3
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.1.12.1/24
            raw_eos_cli: |
              comment
              Comment created from raw_eos_cli under SVI 112 in VRF Common_VRF
              EOF
          "113":
            name: SVI_with_no_vxlan
            tags: [opzone]
            enabled: True
            ip_address_virtual: 10.10.13.1/24
            vxlan: False
#examples of vrf specific cli options
#        raw_eos_cli: |
#          interface Loopback1000
#            description Loopback created from raw_eos_cli under VRF Common_VRF
#        structured_config:
#          domain_list:
#            - structured-config.set.under.vrf.common-vrf
#        bgp:
#          raw_eos_cli: |
#            comment
#            Comment created from raw_eos_cli under BGP for VRF Common_VRF
#            EOF

    # These are pure L2 vlans - so no SVI on l3leafs
    l2vlans:
      "2500":
#        vni_override: 2500
        name: web-l2-vlan
        tags: [web]
      "2600":
#        vni_override: 2600
        name: web-l2-vlan-2
        tags: [web]
      2601:
        name: l2vlan_with_no_vxlan
        tags: [web]
        vxlan: False
        
  Cust_B:
    mac_vrf_vni_base: 20000
    enable_mlag_ibgp_peering_vrfs: true
    vrfs:
      Cust_B_VRF:
        vrf_vni: 2025
        svis:
          "67":
            name: Cust_B_OP_Zone_1
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.32.1.1/24
            structured_config:
              description: set from structured_config on svi (was Cust_B_OP_Zone_1) 
          "211":
#            vni_override: 50211
            name: Cust_B_OP_Zone_2
            tags: [opzone]
            ip_address_virtual: 10.32.11.1/24
          "212":
#            vni_override: 50212
            name: Cust_B_OP_Zone_3
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.32.12.1/24
            nodes:
          213:
            name: SVI_with_no_vxlan
            tags: [opzone]
            enabled: True
            ip_address_virtual: 10.32.13.1/24
            vxlan: False

    # These are pure L2 vlans - so no SVI on l3leafs
    l2vlans:
      "2520":
#        vni_override: 2500
        name: web-l2-vlan
        tags: [web]
      "2620":
#        vni_override: 2600
        name: web-l2-vlan-2
        tags: [web]
      2621:
        name: l2vlan_with_no_vxlan
        tags: [web]
        vxlan: False        
